### ISSUE TITLE
Solve the overlapping markers problem.

### ISSUE THREAD

**Issue by burningthumb** [awiebe/burningthumb-vk-manage#14]
I have several devices at the same location (so they overlap).  I suppose customers could have the same issue.  It seems in fact the world has the issue and the problem has been solved.  Lets implement the solution in our management system to make it uber kool.

http://brandintellect.in/solution-overlapping-markers-google-maps-gmap3-spiderfier/

**Comment by awiebe** [comment]
Alternatively I could just fill the popover with UID links that select the corresponding device, so items at the same address are grouped .

**Comment by burningthumb** [comment]
The solution is to have a way to select overlapping markers - so long as the problem is solved it does not matter how.  But be aware, with GPS the markers may be "close" but not identical so I think the referenced package is doing the "heavy lifting" of finding those overlaps where the location is not identical.

**Comment by awiebe** [comment]
Fixed with SPIDERS!

**Comment by burningthumb** [comment]
Looks good.  Can be closed from my perspective (though Donna disagrees so for v2 we need to talk about this).
