### ISSUE TITLE
Handle booleans correctly in UI

### ISSUE THREAD

**Issue by burningthumb** [awiebe/burningthumb-vk-manage#21]
It seems put.php was not handling true and false strings correctly so booleans were always going into the database as 0.  I have fixed put.php to handle true (0) and false (1) and put the appropriate int values into the database BUT the UI is still always displaying false for the is_rooted_device field.  Take a look at the records for the Dojo MXQ Pro where the is_rooted_device field now has a correct value of 1 but is showing up as false in the UI.  The Kindle, when it next reports, should also report is_rooted_device as 1 since that device is also rooted.  Only the Galaxy S6 is not a rooted device.

**Comment by awiebe** [comment]
Fixed

**Comment by burningthumb** [comment]
Looks fine to me.  Close.
