### ISSUE TITLE
Look in the videokiosk_customer table to lookup device_id -- instead of the devices table

### ISSUE THREAD

**Issue by burningthumb** [awiebe/burningthumb-vk-manage#22]
We have this table called device but it does not represent the purchased devices.  And it seems kinda silly to have to sync the videokiosk_customer table with the devices table since the videokiosk_customer table contains the correct list of devices.  We need to talk about and fix how this is done.  But I believe the device_id should be coming from the videokiosk_customer table.  This came up when I installed the Dojo MXQ Pro which was in the videokiosk_customer table but not in the devices table, put.php was failing because it could not get the device_id (until I manually added the device to the devices table).

**Comment by awiebe** [comment]
Device not in customer record will not be displayed, a device must be created in DB on first post.

**Comment by burningthumb** [comment]
Fixed by having put.php add a record to the device table if one is not found.
