### ISSUE TITLE
BurningThumb Videok Kiosk Management plugin conflicts with Wordpress Media Library

### ISSUE THREAD

**Issue by burningthumb** [awiebe/burningthumb-vk-manage#33]
I tried to add an image to a post and the Media Library hangs forever trying to load image thumbnails.  I disabled the burningthumb-vk-manage plugin and it started working.  Yikes!  This conflict needs to be identified and fixed !!!

**Comment by awiebe** [comment]
Resolved, please reopen if issue reoccurs.
