### ISSUE TITLE
UID Label Overflows into Android ID when table is loaded

### ISSUE THREAD

**Issue by burningthumb** [awiebe/burningthumb-vk-manage#4]
The UID field extents beyond its bounds and overwrites the contents of the Android ID.  Only happens sometimes and it looks like the script is somehow "stuck" as the page is not finished loading.  But I have seen it happen many times.
<img width="1243" alt="screen shot 2017-08-12 at 8 56 03 pm" src="https://user-images.githubusercontent.com/7071216/29246027-e735594e-7fa0-11e7-88bb-839b27ff798f.png">

**Comment by burningthumb** [comment]
Some times the page is fully loaded.  As it was in the attached image.  Notice 1 of the UIDs wraps the the other overwrites the adjacent Android ID field.
<img width="1210" alt="screen shot 2017-08-12 at 9 04 16 pm" src="https://user-images.githubusercontent.com/7071216/29246054-f77f263a-7fa1-11e7-82ba-6cdff36d0fba.png">

**Comment by awiebe** [comment]
Known side effect of floating table header using floatThead, cause uncertain, investigation required.

**Comment by burningthumb** [comment]
Seems to be fixed.  If it re-occurs I'll raise it again.
