### ISSUE TITLE
Map zoom distance is too far

### ISSUE THREAD

**Issue by burningthumb** [awiebe/burningthumb-vk-manage#5]
I like how the zoom happens when the item is clicked but the map is zoomed out too much.  It should be close (maybe this has to do with the fact that some of the devices have no location ?)

Instead of this:

<img width="1211" alt="screen shot 2017-08-12 at 9 08 07 pm" src="https://user-images.githubusercontent.com/7071216/29246070-6a995082-7fa2-11e7-9546-8899325d4014.png">

It should be more like this:

<img width="1249" alt="screen shot 2017-08-12 at 9 09 11 pm" src="https://user-images.githubusercontent.com/7071216/29246075-8c7cfe24-7fa2-11e7-9f35-f20901f37ae2.png">

**Comment by awiebe** [comment]
BY DESIGN
Map is panned not focused when item is selected.  Current zoom distance will be used.

**Comment by awiebe** [comment]
Manifestation of https://github.com/awiebe/burningthumb-vk-manage/issues/12

**Comment by burningthumb** [comment]
Looks fine to me.  Close.
